### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by kiranpate1**
Refactored:
• Responsiveness and arrow component slightly
Added:
• mobile state

Let's use separate components in the future instead of inline ones as seen in here; also we can look to future proof this later on if Superpower guys are OK with that.

### CODE REVIEW

**Review by daybreakstud1o — DISMISSED** [review]
Merge conflict resolved, adding into develop

**Review by daybreakstud1o — APPROVED** [review]
Fixed package lock problem

**Review by alvinleung — COMMENTED** [review]
Approved

**Review by alvinleung — APPROVED** [review]
Approved

**Pull request merged**
